import { translations, type ICompany } from "@/entities/company";
import type { ITableConfig } from "@/widgets/table-with-filters";

export const config: ITableConfig<ICompany> = {
    dataUrl: "/public/get-companies-list",
    filtersUrl: "/public/get-companies-list-filters",
    translations,
    withRowActions: false,
    columnOrder: [
        "company_short_name",
        "company_status",
        "company_inn",
        "company_ogrn",
        "company_type",
        "okved_code",
        "ceo",
        "docs_made",
        "docs_received",
    ],
    hiddenColumns: [
        "id",
        "gid",
        "company_ogrn",
        "company_logo_path",
        "company_gid",
        "company_full_name",
        "company_name",
        "okved_name",
        "company_liquidation_date",
        "parent",
        "cli_type_",
        "cli_status_",
        "name",
        "liquidation_date",
        "is_farmer",
        "is_our",
        "img_path",
        "logo_path",
        "bus_begin",
        "bus_end",
        "tech_description",
        "tech_begin",
        "tech_end",
        "tech_create",
        "tech_change",
        "tech_source",
        "tech_user",
        "cli_jur__id",
        "cli_jur__gid",
        "cli_jur__cli",
        "cli_jur__name",
        // + все cli_jur__* технические поля, если не нужны в публичном списке
    ],
    actions: [],
    refetchOnMount: false,
    enableFilters: true,
};