export { Bio } from "./bio"
export { SystemDetails } from "./system-details"
export { OrganDetails } from "./organ-details"
export { CertDetails } from "./cert-details"
export { DocDetails } from "./doc-details"
export { CompanyDetails } from "./company-details"
export { HomeSystemsSlider } from "./home-systems-slider"
